# Generated by Django 5.1.5 on 2025-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='final_wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
