# Generated by Django 5.1.5 on 2025-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userinfo_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
