# Generated by Django 5.1.5 on 2025-02-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buses',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city1', models.CharField(max_length=255)),
                ('city2', models.CharField(max_length=255)),
                ('stops', models.CharField(max_length=255)),
                ('timetaken_inhrs', models.DecimalField(decimal_places=2, max_digits=25)),
                ('seats', models.CharField(max_length=255)),
            ],
        ),
    ]
