# Generated by Django 5.1.5 on 2025-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='buses',
            name='stops',
        ),
        migrations.AlterField(
            model_name='buses',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddField(
            model_name='buses',
            name='stop',
            field=models.ManyToManyField(to='redbus.stop'),
        ),
    ]
