# Generated by Django 5.1.5 on 2025-02-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
