# Generated by Django 5.1.5 on 2025-02-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('redbus', '0002_stop_remove_buses_stops_alter_buses_slug_buses_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat_booked',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='home.passengers'),
        ),
        migrations.AddField(
            model_name='seat_booked',
            name='tseat_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
