# Generated by Django 5.1.5 on 2025-02-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0003_seat_booked_passengers_seat_booked_tseat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='luxury_seats_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buses',
            name='seats_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buses',
            name='sleeper_seats_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
