# Generated by Django 5.1.5 on 2025-02-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0004_buses_luxury_seats_cost_buses_seats_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat_booked',
            name='final_available_seats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
