# Generated by Django 5.1.5 on 2025-02-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0006_alter_buses_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
