# Generated by Django 5.1.5 on 2025-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0007_alter_buses_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='luxury_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buses',
            name='sleeper_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buses',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
