# Generated by Django 5.1.5 on 2025-02-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0003_buses_arr_time_buses_dep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='timetaken_inhrs',
        ),
    ]
