# Generated by Django 5.1.5 on 2025-02-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0004_remove_buses_timetaken_inhrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='arr_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buses',
            name='dep_time',
            field=models.CharField(max_length=255),
        ),
    ]
